name: iaito
version: '5.9.4'
summary: GUI for radare2
description: |
  Iaito is the official graphical interface for radare2, a libre reverse engineering framework.
  - Focus on simplicity, parity with commands, keybindings and r2-style workflows.
  - Use r2 plugins (f.ex: no need for r2ghidra-iaito plugin if r2ghidra is installed)
  - Aims to cover other radare2 features, not just a disassembler (forensics, networking, bindiffing, solvers, ...).
website: https://www.radare.org/
issues: https://github.com/radareorg/iaito/issues
contact: https://github.com/radareorg/radare2#community
source-code: https://github.com/radareorg/iaito-snap
adopt-info: iaito
confinement: devmode
grade: stable
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: amd64
  arm64:
    build-on: [arm64]
    build-for: arm64
apps:
  iaito:
    common-id: org.radare.iaito.desktop
    command: bin/iaito
    desktop: share/applications/org.radare.iaito.desktop
  r2:
    command: bin/r2
  r2agent:
    command: bin/r2agent
  r2frida-compile:
    command: bin/r2frida-compile
  r2p:
    command: bin/r2p
  r2pm:
    command: bin/r2pm
  r2r:
    command: bin/r2r
  rabin2:
    command: bin/rabin2
  radare2:
    command: bin/radare2
  radiff2:
    command: bin/radiff2
  rafind2:
    command: bin/rafind2
  ragg2:
    command: bin/ragg2
  rahash2:
    command: bin/rahash2
  rarun2:
    command: bin/rarun2
  rasign2:
    command: bin/rasign2
  rasm2:
    command: bin/rasm2
  ravc2:
    command: bin/ravc2
  rax2:
    command: bin/rax2
  sleighc:
    command: bin/sleighc
  yara:
    command: bin/yara
  yarac:
    command: bin/yarac
environment:
  R2_PREFIX: "$SNAP"
  PATH: "$SNAP/bin:$SNAP/usr/bin:${PATH}"
  XDG_DATA_DIRS: "$SNAP/share:$SNAP/usr/share"
  PKG_CONFIG_PATH: "$SNAP/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
  LD_LIBRARY_PATH: "$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
  __EGL_VENDOR_LIBRARY_DIRS: "$SNAP/usr/share/glvnd/egl_vendor.d"
  LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri${LIBGL_DRIVERS_PATH:+:$LIBGL_DRIVERS_PATH}"
  QTDIR: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6"
  QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins"
  QT_QPA_PLATFORM_PLUGIN_PATH: "$SNAP/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt6/plugins/platforms"
  QT_QPA_PLATFORM: "wayland;xcb"
parts:
  radare2:
    plugin: nil
    build-attributes:
      - no-patchelf
    stage-snaps:
      - radare2
    override-stage: |
      craftctl default
      sed -i "s,$CRAFT_STAGE/snap/radare2/current,$CRAFT_STAGE," "$CRAFT_STAGE/lib/pkgconfig/"*.pc
      sed -i "s,/snap/radare2/current,$CRAFT_STAGE," "$CRAFT_STAGE/include/libr/r_userconf.h" "$CRAFT_STAGE/lib/libyara.la"
    prime:
      - "-meta.radare2"
      - "-share/sbom"
    override-prime: |
      craftctl default
      sed -i "s,$CRAFT_STAGE,/snap/$SNAPCRAFT_PROJECT_NAME/current," "$CRAFT_PRIME/lib/pkgconfig/"*.pc "$CRAFT_PRIME/include/libr/r_userconf.h" "$CRAFT_PRIME/lib/libyara.la"
  iaito:
    after:
      - radare2
    plugin: qmake
    source: https://github.com/radareorg/iaito.git
    source-type: git
    source-depth: 1
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    qmake-project-file: src/Iaito.pro
    qmake-parameters:
      - PREFIX=/    
      - -config
      - release
    parse-info:
      - share/metainfo/org.radare.iaito.metainfo.xml
    build-attributes:
      - enable-patchelf
    build-environment:
      - PATH: "/usr/lib/qt6/bin:${PATH}"
    build-packages:
      - pkgconf
      - libgraphviz-dev
      - qt6-base-dev
      - qt6-declarative-dev
      - qt6-svg-dev
    stage-packages:
      - graphviz
      - fonts-agave
      - fonts-anonymous-pro
      - fonts-inconsolata
      # Keyboard I/O
      - libxkbcommon0
      - xkb-data
      # Theming
      - fonts-ubuntu
      - dmz-cursor-theme
      - adwaita-icon-theme
      - qt6-gtk-platformtheme
      - shared-mime-info
      # User Configaration
      - locales-all
      - xdg-user-dirs
      # QT6
      - qt6-wayland
      - libqt6core6t64
      - libqt6gui6t64
      - libqt6network6t64
      - libqt6widgets6
      - libqt6svg6 # also for loading icon themes which are svg
      - libqt6svgwidgets6
      # Other
      - libx11-6
      - libxcb1
      - libgtk-3-common
      - libgtk-3-0t64
      - libglib2.0-bin
      - libnvidia-egl-wayland1
      - libglib2.0-0t64
      - libglib2.0-data
      - gsettings-desktop-schemas
    prime:
      - "-etc"
      - "-usr/bin/X11"
      - "-usr/bin/*qmake6" # Remove QT build files
      - "-usr/lib/*/cmake/*"
      - "-usr/lib/*/qt6/qt6.conf"
      - "-usr/lib/*/qt6/examples"
      - "-usr/lib/X11"
      - "-usr/lib/qt6" # Remove QT build files
      - "-usr/lib/sasl2"
      - "-usr/lib/systemd"
      - "-usr/lib/udev"
      - "-usr/include"
      - "-usr/share/applications"
      - "-usr/share/apport"
      - "-usr/share/bash-completion"
      - "-usr/share/bug"
      - "-usr/share/dbus-1"
      - "-usr/share/doc"
      - "-usr/share/doc-base"
      - "-usr/share/man"
      - "-usr/share/menu"      
      - "-usr/share/pkgconfig"
      - "-usr/share/upstart"
      - "-var"
    override-prime: |
      craftctl default
      ln -s ../../../../../../share/icons/hicolor/scalable/apps/org.radare.iaito.svg "$CRAFT_PRIME"/usr/share/icons/hicolor/scalable/apps/org.radare.iaito.svg
  iaito-translations:
    plugin: nil
    source: https://github.com/radareorg/iaito-translations.git
    source-type: git
    source-depth: 1
    source-branch: master
    build-environment:
      - PATH: "/usr/lib/qt6/bin:${PATH}"
    build-packages:
      - qt6-l10n-tools
    build-attributes:
      - no-patchelf
    override-build: make install PREFIX=$CRAFT_PART_INSTALL
