name: iaito
version: '5.9.4'
summary: GUI for radare2
description: |
  Iaito is the official graphical interface for radare2, a libre reverse engineering framework.
  - Focus on simplicity, parity with commands, keybindings and r2-style workflows.
  - Use r2 plugins (f.ex: no need for r2ghidra-iaito plugin if r2ghidra is installed)
  - Aims to cover other radare2 features, not just a disassembler (forensics, networking, bindiffing, solvers, ...).
website: https://www.radare.org/
issues: https://github.com/radareorg/iaito/issues
contact: https://github.com/radareorg/radare2#community
source-code: https://github.com/radareorg/iaito-snap
adopt-info: iaito
confinement: classic
grade: stable
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: amd64
  arm64:
    build-on: [arm64]
    build-for: arm64
apps:
  iaito:
    common-id: org.radare.iaito.desktop
    command: bin/iaito
    desktop: share/applications/org.radare.iaito.desktop
  r2:
    command: bin/r2
  r2agent:
    command: bin/r2agent
  r2frida-compile:
    command: bin/r2frida-compile
  r2p:
    command: bin/r2p
  r2pm:
    command: bin/r2pm
  r2r:
    command: bin/r2r
  rabin2:
    command: bin/rabin2
  radare2:
    command: bin/radare2
  radiff2:
    command: bin/radiff2
  rafind2:
    command: bin/rafind2
  ragg2:
    command: bin/ragg2
  rahash2:
    command: bin/rahash2
  rarun2:
    command: bin/rarun2
  rasign2:
    command: bin/rasign2
  rasm2:
    command: bin/rasm2
  ravc2:
    command: bin/ravc2
  rax2:
    command: bin/rax2
  sleighc:
    command: bin/sleighc
  yara:
    command: bin/yara
  yarac:
    command: bin/yarac
environment:
  R2_PREFIX: "$SNAP"
  QTWEBENGINEPROCESS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/libexec/QtWebEngineProcess"
  __EGL_VENDOR_LIBRARY_DIRS: "$SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d"
  LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri"
  LD_LIBRARY_PATH: "$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:${LD_LIBRARY_PATH}"
  PKG_CONFIG_PATH: "$SNAP/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
  PATH: "$SNAP/bin:$SNAP/usr/bin:${PATH}"
  XDG_DATA_DIRS: "$SNAP/share:$SNAP/usr/share"
  QT_PLUGIN_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins"
package-repositories:
  - type: apt
    components:
      - main
    suites:
      - noble
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
  radare2:
    plugin: nil
    build-attributes:
      - no-patchelf
    stage-snaps:
      - radare2
    override-stage: |
      craftctl default
      sed -i "s,$CRAFT_STAGE/snap/radare2/current,$CRAFT_STAGE," "$CRAFT_STAGE/lib/pkgconfig/"*.pc
      sed -i "s,/snap/radare2/current,$CRAFT_STAGE," "$CRAFT_STAGE/include/libr/r_userconf.h" "$CRAFT_STAGE/lib/libyara.la"
    prime:
      - "-meta.radare2"
      - "-share/sbom"
    override-prime: |
      craftctl default
      sed -i "s,$CRAFT_STAGE,/snap/$SNAPCRAFT_PROJECT_NAME/current," "$CRAFT_PRIME/lib/pkgconfig/"*.pc "$CRAFT_PRIME/include/libr/r_userconf.h" "$CRAFT_PRIME/lib/libyara.la"
  iaito:
    after:
      - radare2
    plugin: qmake
    source: https://github.com/radareorg/iaito.git
    source-type: git
    source-depth: 1
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    qmake-project-file: src/Iaito.pro
    qmake-parameters:
      - PREFIX=/    
      - -config
      - release
    parse-info:
      - share/metainfo/org.radare.iaito.metainfo.xml
    build-attributes:
      - enable-patchelf
    build-environment:
      - QT_SELECT: "6"
    build-packages:
      - libgraphviz-dev
      - qt6-base-dev
      - qt6-declarative-dev
      - qt6-svg-dev
      - libglx-dev
      - libgl-dev
      - libglvnd-dev
      - libxkbcommon-dev
    stage-packages:
      - graphviz
      - libqt6core6t64
      - libqt6gui6t64
      - libqt6network6t64
      - libqt6widgets6
      - libqt6svg6
      - libqt6svgwidgets6
      - libqt6waylandclient6
      - ibus
      - ibus-wayland
      - fcitx5
      - fcitx5-modules
      - fcitx-mozc
      - libxkbcommon0
    prime:
      - "-usr/lib/*/cmake/*"
      - "-usr/include/*"
      - "-usr/share/applications/*"
      - "-usr/share/doc/*"
      - "-usr/share/docs/*"
      - "-usr/share/ECM/*"
      - "-usr/share/man/*"
      - "-usr/share/pkgconfig"
      - "-usr/bin/X11"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/samba"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_*"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcolordprivate.so.2.0.5"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdrm_amdgpu.so.1.0.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdrm_intel.so.1.0.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdrm_nouveau.so.2.0.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdrm_radeon.so.1.0.1"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libEGL_mesa.so.0.0.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libglapi.so.0.0.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libGLX_mesa.so.0.0.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libharfbuzz-gobject.so.0.60830.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicuio.so.74.2"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicutest.so.74.2"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicutu.so.74.2"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libLLVM-17.so.1"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpangoxft-1.0.so.0.5200.1"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpciaccess.so.0.11.1"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpresage.so.1.1.1"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6QuickWidgets.so.6.7.2"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsensors.so.5.0.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libtinyxml.so.2.6.2"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvulkan.so.1.3.275"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb-dri2.so.0.0.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb-dri3.so.0.1.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb-present.so.0.0.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libXft.so.2.3.6"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxshmfence.so.1.0.0"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libXxf86vm.so.1.0.0"
      - "-var"
  iaito-translations:
    plugin: nil
    source: https://github.com/radareorg/iaito-translations.git
    source-type: git
    source-depth: 1
    source-branch: master
    build-environment:
      - QT_SELECT: "6"
    build-packages:
      - qtchooser
      - qt6-l10n-tools
    build-attributes:
      - no-patchelf
    override-build: make install PREFIX=$CRAFT_PART_INSTALL
