name: iaito
version: '5.9.4'
summary: GUI for radare2
description: |
  Iaito is the official graphical interface for radare2, a libre reverse engineering framework.
  - Focus on simplicity, parity with commands, keybindings and r2-style workflows.
  - Use r2 plugins (f.ex: no need for r2ghidra-iaito plugin if r2ghidra is installed)
  - Aims to cover other radare2 features, not just a disassembler (forensics, networking, bindiffing, solvers, ...).
website: https://www.radare.org/
issues: https://github.com/radareorg/iaito/issues
contact: https://github.com/radareorg/radare2#community
source-code: https://github.com/radareorg/iaito-snap
adopt-info: iaito
confinement: classic
grade: stable
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: amd64
  arm64:
    build-on: [arm64]
    build-for: arm64
apps:
  iaito:
    common-id: org.radare.iaito.desktop
    command: bin/iaito
    desktop: share/applications/org.radare.iaito.desktop
  r2:
    command: bin/r2
  r2agent:
    command: bin/r2agent
  r2frida-compile:
    command: bin/r2frida-compile
  r2p:
    command: bin/r2p
  r2pm:
    command: bin/r2pm
  r2r:
    command: bin/r2r
  rabin2:
    command: bin/rabin2
  radare2:
    command: bin/radare2
  radiff2:
    command: bin/radiff2
  rafind2:
    command: bin/rafind2
  ragg2:
    command: bin/ragg2
  rahash2:
    command: bin/rahash2
  rarun2:
    command: bin/rarun2
  rasign2:
    command: bin/rasign2
  rasm2:
    command: bin/rasm2
  ravc2:
    command: bin/ravc2
  rax2:
    command: bin/rax2
  sleighc:
    command: bin/sleighc
  yara:
    command: bin/yara
  yarac:
    command: bin/yarac
environment:
  R2_PREFIX: "$SNAP"
  SLEIGHHOME: "$SNAP/lib/radare2/last"
  PATH: "$SNAP/bin:$SNAP/usr/bin:${PATH}"
  XDG_DATA_DIRS: "$SNAP/share:$SNAP/usr/share"
  PKG_CONFIG_PATH: "$SNAP/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}"
  LD_LIBRARY_PATH: "$SNAP/lib:$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
  __EGL_VENDOR_LIBRARY_DIRS: "$SNAP/usr/share/glvnd/egl_vendor.d"
  LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri${LIBGL_DRIVERS_PATH:+:$LIBGL_DRIVERS_PATH}"
parts:
  radare2:
    plugin: nil
    build-attributes:
      - no-patchelf
    stage-snaps:
      - radare2
    stage:
      - "-meta.radare2"
      - "-share/sbom"
    override-stage: |
      craftctl default
      sed -i "s,$CRAFT_STAGE/snap/radare2/current,$CRAFT_STAGE," "$CRAFT_STAGE/lib/pkgconfig/"*.pc
      sed -i "s,/snap/radare2/current,$CRAFT_STAGE," "$CRAFT_STAGE/include/libr/r_userconf.h" "$CRAFT_STAGE/lib/libyara.la"
    override-prime: |
      craftctl default
      sed -i "s,$CRAFT_STAGE,/snap/$SNAPCRAFT_PROJECT_NAME/current," "$CRAFT_PRIME/lib/pkgconfig/"*.pc "$CRAFT_PRIME/include/libr/r_userconf.h" "$CRAFT_PRIME/lib/libyara.la"
  iaito:
    after:
      - radare2
    plugin: qmake
    source: https://github.com/radareorg/iaito.git
    source-type: git
    source-depth: 1
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    qmake-project-file: src/Iaito.pro
    qmake-parameters:
      - PREFIX=/    
      - -config
      - release
    parse-info:
      - share/metainfo/org.radare.iaito.metainfo.xml
    build-attributes:
      - enable-patchelf
    build-environment:
      - PATH: "/usr/lib/qt6/bin:${PATH}"
    build-packages:
      - pkgconf
      - libgraphviz-dev
      - qt6-base-dev
      - qt6-declarative-dev
      - qt6-svg-dev
    override-build: |
      craftctl default
      sed -i -e "s,Icon=\(.*\)\$,Icon=/share/icons/hicolor/scalable/apps/\1.svg," "$CRAFT_PART_INSTALL"/share/applications/org.radare.iaito.desktop
    stage-packages:
      - graphviz
      - fonts-agave
      - fonts-anonymous-pro
      - fonts-inconsolata
      # X11 + wayland
      - xkb-data
      - libx11-6
      - libxcb1
      - libxkbcommon0
      - libnvidia-egl-wayland1
      # Theming
      - fonts-ubuntu
      - dmz-cursor-theme
      - adwaita-icon-theme
      - qt6-gtk-platformtheme
      - libgtk-3-common
      - libgtk-3-0t64
      - libglib2.0-0t64
      - libglib2.0-data
      - gsettings-desktop-schemas
      - shared-mime-info
      # User Configaration
      - locales-all
      - xdg-user-dirs
      # QT6
      - qt6-wayland
      - libqt6core6t64
      - libqt6gui6t64
      - libqt6network6t64
      - libqt6widgets6t64
      - libqt6svg6 # also for loading icon themes which are svg
      - libqt6svgwidgets6
    prime:
      # Remove nondesired base paths
      - "-etc"
      - "-usr/bin/X11"
      - "-usr/include"
      - "-usr/libexec"
      - "-var"
      # Remove QT build and examples files
      - "-usr/bin/*qmake6"
      - "-usr/lib/qt6"
      - "-usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt6/qt6.conf"
      - "-usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt6/examples"
      # Remove QT QML (unused)
      - "-usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt6/qml"
      - "-usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt6/plugins/qml*"
      # The libraries in .../qt6/plugins need to not be patched otherwise snapcraft may strip the QT metadata
      - "-usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt6/plugins"
      # Remove nondesired libary files
      - "-usr/lib/X11"
      - "-usr/lib/sasl2"
      - "-usr/lib/systemd"
      - "-usr/lib/udev"
      # The libraries in .../dri need no-patchelf, so they come from the mesa-unpatched part
      - "-usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/dri"
      # Remove nondesired metadata
      - "-usr/share/applications"
      - "-usr/share/apport"
      - "-usr/share/bash-completion"
      - "-usr/share/bug"
      - "-usr/share/dbus-1"
      - "-usr/share/doc"
      - "-usr/share/doc-base"
      - "-usr/share/man"
      - "-usr/share/menu"      
      - "-usr/share/pkgconfig"
      - "-usr/share/upstart"
  iaito-translations:
    plugin: nil
    source: https://github.com/radareorg/iaito-translations.git
    source-type: git
    source-depth: 1
    source-branch: master
    build-environment:
      - PATH: "/usr/lib/qt6/bin:${PATH}"
    build-packages:
      - qt6-l10n-tools
    build-attributes:
      - no-patchelf
    override-build: make install PREFIX=$CRAFT_PART_INSTALL
  mesa-no-patchelf:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
    build-attributes:
      - no-patchelf # Otherwise snapcraft may strip the build ID and cause the driver to crash
    stage:
      # Only the libraries in .../dri need to not be patched, the rest come from the mesa part
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/dri
  qtplugins-no-patchelf:
    plugin: nil
    stage-packages:
      - qt6-wayland
      - libqt6gui6t64
      - libqt6network6t64
      - libqt6svg6
    build-attributes:
      - no-patchelf # Otherwise snapcraft may strip the QT metadata
    stage:
      # Only the libraries in .../qt6/plugins need to not be patched
      - usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/qt6/plugins
  qtconf:
    plugin: nil
    override-build: |
      mkdir -p "$CRAFT_PART_INSTALL"/bin
      cat <<EOF > "$CRAFT_PART_INSTALL"/bin/qt.conf
      [Paths]
      Prefix = ..
      ArchData=usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6
      Binaries=usr/lib/qt6/bin
      Data=usr/share/qt6
      Documentation=usr/share/qt6/doc
      Headers=include/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6
      HostBinaries=usr/lib/qt6/bin
      HostData=usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6
      HostLibraries=usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      Libraries=usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      LibraryExecutables=usr/lib/qt6/libexec
      Plugins=usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
      Qml2Imports=usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/qml
      Settings=/snap/iaito/current/etc/xdg
      Translations=share/iaito/translations
      EOF
