name: iaito
version: '5.9.4'
website: https://www.radare.org/
issues: https://github.com/radareorg/iaito/issues
contact: https://github.com/radareorg/radare2#community
source-code: https://github.com/radareorg/iaito-snap.git
license: LGPL-3.0-only
adopt-info: iaito
confinement: classic
grade: stable
base: core22
platforms:
  amd64:
    build-on: [amd64]
    build-for: amd64
  arm64:
    build-on: [arm64]
    build-for: arm64
slots:
  session-dbus-interface:
    interface: dbus
    name: org.radare.iaito
    bus: session
apps:
  iaito:
    common-id: org.radare.iaito.desktop
    command: iaito
    extensions: [kde-neon-6]
parts:
  iaito:
    plugin: qmake
    source: https://github.com/radareorg/iaito.git
    source-type: git
    source-depth: 1
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-subdir: src
    parse-info:
      - usr/share/metainfo/org.radare.iaito.metainfo.xml
    prime:
      - -usr/lib/*/qmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/share/lintian
  iaito-translations:
    after:
      - iaito
    plugin: make
    source: https://github.com/radareorg/iaito-translations.git
    source-type: git
    source-depth: 1
    source-branch: master
    make-parameters:
      - install
      - PREFIX=$CRAFT_PART_INSTALL
  cleanup:
    after:
      - iaito
    plugin: nil
    build-snaps:
      - core22
      - kf6-core22
      - qt-common-themes
    override-prime: |
      set -eux
      for snap in "core22" "kf6-core22" "qt-common-themes"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done