name: iaito
version: '5.9.4'
website: https://www.radare.org/
issues: https://github.com/radareorg/iaito/issues
source-code: https://github.com/radareorg/iaito-snap.git
adopt-info: iaito
confinement: classic
grade: stable
base: core22
assumes:
  - snapd2.58.3
architectures:
  - build-on: [amd64]
    build-for: amd64
  - build-on: [arm64]
    build-for: arm64
apps:
  iaito:
    common-id: org.radare.iaito.desktop
    command: iaito
    desktop: usr/share/applications/org.radare.iaito.desktop
environment:
  QTWEBENGINEPROCESS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/libexec/QtWebEngineProcess"
  __EGL_VENDOR_LIBRARY_DIRS: "$SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d"
  LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri"
  LD_LIBRARY_PATH: ":$SNAP/usr/lib:$SNAP/lib/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:${LD_LIBRARY_PATH}"
  PATH: $SNAP/usr/bin:${PATH}
  XDG_DATA_DIRS: $SNAP/usr/share:$SNAP/usr/share:$SNAP/data-dir
  QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
layout:
  /usr/share/X11:
    symlink: $SNAP/usr/share/X11
  /usr/share/qt6:
    bind: $SNAP/usr/share/qt6
package-repositories:
  - type: apt
    components:
      - main
    suites:
      - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
  mesa-patchelf:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
      - freeglut3
      - libglu1-mesa
    stage:
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri"
  mesa-no-patchelf:
    plugin: nil
    stage-packages:
      - libgl1-mesa-dri
    build-attributes:
      - no-patchelf
    stage:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri
  qtconf:
    plugin: nil
    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      cat <<EOF > $CRAFT_PART_INSTALL/usr/bin/qt.conf
      [Paths]
      Prefix = ../../
      LibraryExecutables = usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/libexec
      Plugins = usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
      Qml2Imports = usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/qml
      Translations = usr/share/qt6/translations
      Data = usr/share/qt6
      EOF
  iaito:
    after:
      - mesa-patchelf
      - mesa-no-patchelf
      - qtconf
    plugin: qmake
    source: https://github.com/radareorg/iaito.git
    source-type: git
    source-depth: 1
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-subdir: src
    parse-info:
      - usr/share/metainfo/org.radare.iaito.metainfo.xml
    build-attributes:
      - enable-patchelf
    build-environment:
      - PATH: /snap/radare2/current/bin:/snap/kde-qt6-core22-sdk/current/usr/bin:/snap/kf6-core22-sdk/current/usr/bin${PATH:+:$PATH}
      - XDG_DATA_DIRS: $CRAFT_STAGE/usr/share:/snap/kde-qt6-core22-sdk/current/usr/share:/snap/kf6-core22-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
      - XDG_CONFIG_HOME: $CRAFT_STAGE/etc/xdg:/snap/kde-qt6-core22-sdk/current/etc/xdg:/snap/kf6-core22-sdk/current/etc/xdg:/etc/xdg${XDG_CONFIG_HOME:+:$XDG_CONFIG_HOME}
      - LD_LIBRARY_PATH: /snap/radare2/current/lib:/snap/kde-qt6-core22-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/kde-qt6-core22-sdk/current/usr/lib:/snap/kf6-core22-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/kf6-core22-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/blas:/snap/kf6-core22-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/lapack:/snap/kf6-core22-sdk/current/usr/lib:$CRAFT_STAGE/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      - PKG_CONFIG_PATH: /snap/radare2/current/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    build-snaps:
      - radare2
      - kde-qt6-core22-sdk
      - kf6-core22-sdk
    build-packages:
      - graphviz
      - libglx-dev
      - libgl-dev
      - libglvnd-dev
      - libxkbcommon-dev
      - libpulse0
    stage-snaps:
      - kf6-core22
      - qt-common-themes
    stage-packages:
      - graphviz
      - ibus
      - ibus-wayland
      - fcitx5
      - fcitx5-modules
      - fcitx-mozc
      - libxkbcommon0
      - libpulse0
    prime:
      - "-usr/lib/*/cmake/*"
      - "-usr/include/*"
      - "-usr/share/ECM/*"
      - "-usr/share/man/*"
      - "-usr/bin/X11"
      - "-usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0"
      - "-usr/lib/aspell/*"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri"
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsvn_auth_kwallet-1.so.1.0.0
      - -lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libulockmgr.so.1.0.1
      - -lib32/*
      - -usr/lib/libhardsid-builder.so.0.0.1
      - -usr/lib/llvm-14/lib/libLTO.so.14
      - -usr/lib/llvm-14/lib/libRemarks.so.14
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libEGL_mesa.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libGLESv1_CM.so.1.2.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libGLX_mesa.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKDEGames6Private.so.6.0.240770
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKF6CalendarEvents.so.6.4.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKF6DAV.so.6.4.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKF6ModemManagerQt.so.6.4.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKF6PeopleWidgets.so.6.4.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKF6Runner.so.6.4.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKF6TextAutoCorrectionWidgets.so.1.5.45
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKF6TextGrammarCheck.so.1.5.45
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKF6ThreadWeaver.so.6.4.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKF6UnitConversion.so.6.4.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKWaylandClient.so.6.0.3
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKWaylandClient.so.6.1.3
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libOpenEXRUtil-3_1.so.30.11.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQCoro6DBus.so.0.10.80
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQCoro6Network.so.0.10.80
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQCoro6Qml.so.0.10.80
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQCoro6Quick.so.0.10.80
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQCoro6WebSockets.so.0.10.80
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6Bluetooth.so.6.7.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6Coap.so.6.7.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6HttpServer.so.6.7.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6Mqtt.so.6.7.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6MultimediaWidgets.so.6.7.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6NetworkAuth.so.6.7.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6Nfc.so.6.7.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6PdfWidgets.so.6.7.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQt6SvgWidgets.so.6.7.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_bad_any_cast_impl.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_bad_optional_access.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_bad_variant_access.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_civil_time.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_failure_signal_handler.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_hashtablez_sampler.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_log_severity.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_periodic_sampler.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_random_distributions.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_random_internal_distribution_test_util.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_random_seed_sequences.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_scoped_set_env.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_strerror.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libasan.so.6.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libatomic.so.1.2.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcaca++.so.0.99.19
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcairo-script-interpreter.so.2.11600.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcolordprivate.so.2.0.5
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libcupsimage.so.2
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdbusmenu-qt6.so.2.6.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdcerpc-server-core.so.0.0.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdcerpc-server.so.0.0.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libfaad_drm.so.2.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_grapheme_lang.so.2.2
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_grapheme_lex.so.2.2
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_indic_lex.so.2.2
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_time_awb.so.2.2
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgccpp.so.1.4.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstcheck-1.0.so.0.2003.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstcontroller-1.0.so.0.2003.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgthread-2.0.so.0.7200.4
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libharfbuzz-gobject.so.0.20704.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libharfbuzz-icu.so.0.20704.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libheif.so.1.12.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libhwy_contrib.so.1.0.7
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libhwy_test.so.1.0.7
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libib_util.so
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libical-glib.so.3.0.14
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicalss_cxx.so.3.0.14
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicutest.so.70.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libigdgmm.so.12.1.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libitm.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjacknet.so.0.1.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjackserver.so.0.1.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjansson.so.4.13.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libjxl_extras_codec.so.0.10.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libkadm5clnt_mit.so.12.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libkadm5srv_mit.so.12.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libkdecorations2.so.6.1.80
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libkdecorations2private.so.6.1.80
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libkdsoap-server-qt6.so.2.2.95
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblber-2.5.so.0.1.12
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libldap-2.5.so.0.1.12
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblsan.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblttng-ust-ctl.so.5.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblttng-ust-cyg-profile-fast.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblttng-ust-cyg-profile.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblttng-ust-dl.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblttng-ust-fd.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblttng-ust-fork.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblttng-ust-libc-wrapper.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblttng-ust-pthread-wrapper.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblttng-ust-python-agent.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblua5.2-c++.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libmd4c-html.so.0.4.8
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libmfx-tracer.so.1.35
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libmfxhw64.so.1.35
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libmpeg2convert.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libnetapi.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libobjc.so.4.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libobjc_gc.so.4.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libodbccr.so.2.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libodbcinst.so.2.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liborc-test-0.4.so.0.32.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liboxygenstyle6.so.6.1.80
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liboxygenstyleconfig6.so.6.1.80
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpcre16.so.3.13.3
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpcre2-32.so.0.10.4
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpcre2-posix.so.3.0.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpcre32.so.3.13.3
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpcrecpp.so.0.0.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libphonon4qt6experimental.so.4.12.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpolkit-qt6-agent-1.so.1.200.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpolkit-qt6-gui-1.so.1.200.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpresage.so.1.1.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libraw_r.so.20.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsamba-passdb.so.0.28.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsamba-policy.cpython-310-x86-64-linux-gnu.so.0.0.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsctp.so.1.0.19
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsmbldap.so.2.1.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsoup-2.4.so.1.11.2
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsphinxad.so.3.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsquashfuse_ll.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libssl3.so
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsvn_auth_gnome_keyring-1.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsvn_auth_kwallet-1.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libtiffxx.so.5.7.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libtsan.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libubsan.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libunwind-coredump.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libunwind-ptrace.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libunwind-x86_64.so.8.0.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liburcu-bp.so.8.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liburcu-cds.so.8.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liburcu-common.so.8.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liburcu-mb.so.8.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liburcu-memb.so.8.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liburcu-qsbr.so.8.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liburcu-signal.so.8.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liburcu.so.8.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libva-glx.so.2.1400.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb-dpms.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb-record.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb-screensaver.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb-xf86dri.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb
      - -usr/lib32/libstdc++.so.6.0.30
      - -usr/lib32/libgcc_s.so.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/preloadable_libintl.so
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libzvbi-chains.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libz3.so.4
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb-xvmc.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb-xtest.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb-xrm.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxcb-xinput.so.0.1.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libtinyxml.so.2.6.2
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpolkit-agent-1.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblttng-ust.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libkdsoap-qt6.so.2.2.95
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libkdb5.so.10.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicutest.so.70.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libical_cxx.so.3.0.14
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgif.so.7.1.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgc.so.1.4.4
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libfuseprivate.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libflite_cmu_indic_lang.so.2.2
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libde265.so.0.1.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_random_internal_pool_urbg.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_exponential_biased.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_examine_stack.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libQCoro6Core.so.0.10.80
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libOpenEXRCore-3_1.so.30.11.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libKF6TextAutoCorrectionCore.so.1.5.45
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libGLX_mesa.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/samba/libnet-keytab.so.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins/multimedia
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libxxhash.so.0.8.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libvulkan.so.1.3.204
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libv4l2rds.so.0.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/liblttng-ust-tracepoint.so.1.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libicutest.so.70.1
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstgl-1.0.so.0.2001.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgssrpc.so.4.2
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libavisynth.so.3.7.3
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_random_seed_gen_exception.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_random_internal_seed_material.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libabsl_random_internal_randen.so.20210324.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libGLX_mesa.so.0.0.0
      - -lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libfuse.so.2.9.9
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/samba
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libsphinxbase.so.3.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpocketsphinx.so.3.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libndr.so.2.0.0
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libexec/kf6/smbnotifier
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libdcerpc.so.0.0.1
  iaito-translations:
    after:
      - iaito
    plugin: nil
    source: https://github.com/radareorg/iaito-translations.git
    source-type: git
    source-depth: 1
    source-branch: master
    override-build: make install PREFIX=$CRAFT_PART_INSTALL/usr
