name: iaito
version: '5.9.4'
summary: GUI for radare2
description: |
  Iaito is the official graphical interface for radare2, a libre reverse engineering framework.
  - Focus on simplicity, parity with commands, keybindings and r2-style workflows.
  - Use r2 plugins (f.ex: no need for r2ghidra-iaito plugin if r2ghidra is installed)
  - Aims to cover other radare2 features, not just a disassembler (forensics, networking, bindiffing, solvers, ...).
website: https://www.radare.org/
issues: https://github.com/radareorg/iaito/issues
contact: https://github.com/radareorg/radare2#community
source-code: https://github.com/radareorg/iaito-snap.git
adopt-info: iaito
confinement: classic
grade: stable
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: amd64
  arm64:
    build-on: [arm64]
    build-for: arm64
apps:
  iaito:
    common-id: org.radare.iaito.desktop
    command: iaito
    desktop: usr/share/applications/org.radare.iaito.desktop
environment:
  QTWEBENGINEPROCESS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/libexec/QtWebEngineProcess"
  __EGL_VENDOR_LIBRARY_DIRS: "$SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d"
  LIBGL_DRIVERS_PATH: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri"
  LD_LIBRARY_PATH: "$SNAP/usr/lib:$SNAP/lib/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:${LD_LIBRARY_PATH}"
  PATH: $SNAP/usr/bin:${PATH}
  XDG_DATA_DIRS: $SNAP/usr/share
  QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
package-repositories:
  - type: apt
    components:
      - main
    suites:
      - noble
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com
parts:
  iaito:
    plugin: autotools
    source: https://github.com/radareorg/iaito.git
    source-type: git
    source-depth: 1
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    autotools-configure-parameters:
      - "--prefix=$CRAFT_PART_INSTALL/usr"
    parse-info:
      - usr/share/metainfo/org.radare.iaito.metainfo.xml
    build-attributes:
      - enable-patchelf
    build-environment:
      - QT_SELECT: "6"
      - PATH: /snap/radare2/current/bin:/usr/bin:${PATH:+:$PATH}
      - LD_LIBRARY_PATH: /snap/radare2/current/lib:$CRAFT_STAGE/usr/lib:$CRAFT_STAGE/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      - PKG_CONFIG_PATH: /snap/radare2/current/lib/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    build-snaps:
      - radare2
    build-packages:
      - libgraphviz-dev
      - qt6-base-dev
      - qt6-declarative-dev
      - qt6-svg-dev
      - libglx-dev
      - libgl-dev
      - libglvnd-dev
      - libxkbcommon-dev
    stage-snaps:
      - qt-common-themes
    stage-packages:
      - graphviz
      - libqt6core6t64
      - libqt6gui6t64
      - libqt6network6t64
      - libqt6widgets6
      - libqt6svg6
      - libqt6svgwidgets6
      - libqt6waylandclient6
      - ibus
      - ibus-wayland
      - fcitx5
      - fcitx5-modules
      - fcitx-mozc
      - libxkbcommon0
    prime:
      - "-usr/lib/*/cmake/*"
      - "-usr/include/*"
      - "-usr/share/ECM/*"
      - "-usr/share/man/*"
      - "-usr/share/pkgconfig"
      - "-usr/bin/X11"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri"
      - "-usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/samba"
  iaito-translations:
    plugin: nil
    source: https://github.com/radareorg/iaito-translations.git
    source-type: git
    source-depth: 1
    source-branch: master
    build-environment:
      - QT_SELECT: "6"
    build-packages:
      - qtchooser
      - qt6-l10n-tools
    override-build: make install PREFIX=$CRAFT_PART_INSTALL/usr
